# For more information: https://laravel.com/docs/sail
version: '3'
services:
  myapp:
    build:
      context: ./docker/8.0
      dockerfile: Dockerfile
    image: sail-8.0/app
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
  adminer:
    container_name: goshop_adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    volumes:
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini
    command: php -S 0.0.0.0:8080 -t /var/www/html # Fix "getaddrinfo failed: Name does not resolve"
    networks:
      - sail
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
  # memcached:
  #     image: 'memcached:alpine'
  #     ports:
  #         - '11211:11211'
  #     networks:
  #         - sail
  # mailhog:
  #     image: 'mailhog/mailhog:latest'
  #     ports:
  #         - 1025:1025
  #         - 8025:8025
  #     networks:
  #         - sail
  nginx:
    container_name: app-nginx
    image: 'nginx:alpine'
    ports:
      - "5000:80"
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/8.0/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - myapp
      - mysql
      - redis
      - echo_server
    networks:
      - sail
  echo_server:
    container_name: echo_server
    build:
      context: ./docker/laravel-echo-server
      dockerfile: Dockerfile
    volumes:
      - .env:/app/.env
      - ./docker/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json
    restart: unless-stopped
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
